version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.13.0
    working_directory: ~/repo

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Clean up Node.js modules and package-lock
          command: |
            rm -rf node_modules
            rm -f package-lock.json
      - run:
          name: Install system dependencies
          command: |
            sudo dpkg --add-architecture i386
            sudo apt-get update
            sudo apt-get install -y wine64 wine32
      - run:
          name: Install Node.js dependencies
          command: npm install
      - run:
          name: Rebuild sqlite3
          command: npm run rebuild
      - run:
          name: Build the application
          command: npm run build
      - run:
          name: Compress Artifacts
          command: |
            # Install zip if not available, for Debian/Ubuntu
            sudo apt-get update && sudo apt-get install -y zip
            # Compress the directory
            zip -r release-win-unpacked.zip release/win-unpacked
      - store_artifacts:
          path: release-win-unpacked.zip
          destination: release_files
workflows:
  version: 2
  build:
    jobs:
      - build
